version: '3.4'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - 14333:1433
    container_name: mssql
    restart: on-failure
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=Lwz3.131492653 
    networks:
      - mssql
    volumes:
      - mssqldata:/var/lib/mssql/data

networks:
  mssql:
    driver: bridge
    
  
volumes:
  mssqldata:
    driver: local
