// <auto-generated />
using System;
using EFCore.Oracle.Demo;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

namespace EFCore.Oracle.Demo2.Migrations
{
    [DbContext(typeof(BloggingContext))]
    [Migration("20191025061047_init_20191025")]
    partial class init_20191025
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("Relational:Sequence:.Blogs_BlogId_sq1", "'Blogs_BlogId_sq1', '', '1', '10', '', '', 'Int64', 'False'")
                .HasAnnotation("Relational:Sequence:.Posts_PostId_sq3", "'Posts_PostId_sq3', '', '1', '10', '', '', 'Int64', 'False'")
                .HasAnnotation("Relational:Sequence:.SdfeyHisMedicineInLog_Id_sq1", "'SdfeyHisMedicineInLog_Id_sq1', '', '1', '10', '', '', 'Int64', 'False'")
                .HasAnnotation("Relational:Sequence:.SdfeyHisOutPatientInfo_Id_sq1", "'SdfeyHisOutPatientInfo_Id_sq1', '', '1', '10', '', '', 'Int64', 'False'");

            modelBuilder.Entity("EFCore.Oracle.Demo.Blog", b =>
                {
                    b.Property<int>("BlogId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("Oracle:HiLoSequenceName", "Blogs_BlogId_sq1")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.SequenceHiLo);

                    b.Property<string>("Url");

                    b.HasKey("BlogId");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("EFCore.Oracle.Demo.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("Oracle:HiLoSequenceName", "Posts_PostId_sq3")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.SequenceHiLo);

                    b.Property<int>("BlogId");

                    b.Property<string>("Content");

                    b.Property<string>("Title");

                    b.HasKey("PostId");

                    b.HasIndex("BlogId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("EFCore.Oracle.Demo2.Entity.Hids.His.SdfeyHisMedicineInLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("Oracle:HiLoSequenceName", "SdfeyHisMedicineInLog_Id_sq1")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.SequenceHiLo);

                    b.Property<decimal?>("Amount");

                    b.Property<string>("CardNo");

                    b.Property<string>("CommonName");

                    b.Property<string>("DeptCode");

                    b.Property<string>("DeptName");

                    b.Property<string>("IdentityNo");

                    b.Property<string>("InsuranceNo");

                    b.Property<string>("InsuranceType");

                    b.Property<string>("MedicineName");

                    b.Property<string>("MedicineType");

                    b.Property<DateTime?>("OperDate");

                    b.Property<string>("PatientId");

                    b.Property<string>("PatientName");

                    b.Property<decimal?>("Quantity");

                    b.Property<string>("Stock_Code");

                    b.Property<string>("Stock_Name");

                    b.Property<string>("Unit");

                    b.Property<decimal?>("UnitPrice");

                    b.HasKey("Id");

                    b.ToTable("SdfeyHisMedicineInLog");
                });

            modelBuilder.Entity("EFCore.Oracle.Demo2.Entity.Hids.His.SdfeyHisOutPatientInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("Oracle:HiLoSequenceName", "SdfeyHisOutPatientInfo_Id_sq1")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.SequenceHiLo);

                    b.Property<string>("Address");

                    b.Property<DateTime>("Birthday");

                    b.Property<string>("CertNo");

                    b.Property<string>("CertType");

                    b.Property<string>("Contatct");

                    b.Property<string>("ContatctMobile");

                    b.Property<string>("ContatctPhone");

                    b.Property<string>("InsuranceNo");

                    b.Property<string>("InsuranceType");

                    b.Property<string>("OutPatientDepartment");

                    b.Property<string>("OutPatientDoctor");

                    b.Property<string>("OutPatientNo");

                    b.Property<string>("PatientId");

                    b.Property<string>("PatientName");

                    b.Property<string>("RelationShip");

                    b.Property<DateTime>("SeeDate");

                    b.Property<string>("Sex");

                    b.HasKey("Id");

                    b.ToTable("SdfeyHisOutPatientInfo");
                });

            modelBuilder.Entity("EFCore.Oracle.Demo.Post", b =>
                {
                    b.HasOne("EFCore.Oracle.Demo.Blog", "Blog")
                        .WithMany("Posts")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
