// <auto-generated />
using EFCore.Oracle.Demo;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

namespace EFCore.Oracle.Demo2.Migrations
{
    [DbContext(typeof(BloggingContext))]
    [Migration("20191025044115_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("Relational:Sequence:.Blogs_BlogId_sq1", "'Blogs_BlogId_sq1', '', '1', '10', '', '', 'Int64', 'False'")
                .HasAnnotation("Relational:Sequence:.Posts_PostId_sq3", "'Posts_PostId_sq3', '', '1', '10', '', '', 'Int64', 'False'");

            modelBuilder.Entity("EFCore.Oracle.Demo.Blog", b =>
                {
                    b.Property<int>("BlogId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("Oracle:HiLoSequenceName", "Blogs_BlogId_sq1")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.SequenceHiLo);

                    b.Property<string>("Url");

                    b.HasKey("BlogId");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("EFCore.Oracle.Demo.Post", b =>
                {
                    b.Property<int>("PostId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("Oracle:HiLoSequenceName", "Posts_PostId_sq3")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.SequenceHiLo);

                    b.Property<int>("BlogId");

                    b.Property<string>("Content");

                    b.Property<string>("Title");

                    b.HasKey("PostId");

                    b.HasIndex("BlogId");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("EFCore.Oracle.Demo.Post", b =>
                {
                    b.HasOne("EFCore.Oracle.Demo.Blog", "Blog")
                        .WithMany("Posts")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
