version: '3.3'

networks:
  exceptionless_default:
    external: true

services:
  oap:
    image: skywalking/oap
    container_name: oap
    restart: always
    ports:
      - 11801:11800
      - 12801:12800
    environment:
      SW_STORAGE: elasticsearch
      SW_STORAGE_ES_CLUSTER_NODES: elasticsearch:9200
    networks:
      - exceptionless_default
  ui:
    image: skywalking/ui
    container_name: ui
    depends_on:
      - oap
    links:
      - oap
    restart: always
    ports:
      - 8081:8080
    environment:
      SW_OAP_ADDRESS: oap:12801
    networks:
      - exceptionless_default
        