version: '3.7'

volumes: 
  drone_data: {}
  
services: 
  drone: 
    image: drone/drone:1
    container_name: drone
    restart: always
    ports: 
      - 8080:80
      - 8443:443
    environment: 
      - DRONE_GOGS_SERVER=http://192.168.88.101:3000
      - DRONE_GOGS_SKIP_VERIFY=true
      - DRONE_SERVER_HOST=192.168.88.101:8080
      - DRONE_SERVER_PROTO=http
      - DRONE_RUNNER_CAPACITY=2
    volumes: 
      - /var/run/docker.sock:/var/run/docker.sock
      - drone_data:/data