# Use root/example as user/password credentials
version: '3.7'

services: 
  consul1: 
    image: consul:latest
    container_name: consul1
    restart: always
    ports: 
      - 8300:8300
      - 8301:8301
      - 8301:8301/udp
      - 8302:8302
      - 8302:8302/udp
      - 8500:8500
      - 8600:8600
      - 8600:8600/udp
    command: agent -server -client=0.0.0.0 -bind=0.0.0.0 -advertise=192.168.88.101  -ui -bootstrap-expect=1 -node=consul1