version: '2.2'

volumes: 
  kong_data: {}

networks: 
  kong-net: 

services: 
  kong-database: 
    image: postgres:11.2-alpine
    container_name: kong-database
    environment: 
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kong
      POSTGRES_USER: kong
    healthcheck: 
      test: ["CMD", "pg_isready", "-d", "kong", "-U", "kong"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: on-failure
    stdin_open: true
    tty: true
    networks: 
      - kong-net
    volumes: 
      - kong_data:/var/lib/postgresql/data
      
  kong-migrations: 
    image: kong:latest
    container_name: kong-migrations
    command: kong migrations bootstrap
    depends_on: 
      kong-database: 
        condition: service_healthy
    environment: 
      KONG_DATABASE: postgres
      KONG_PG_DATABASE: kong
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kong
      KONG_PG_USER: kong
    networks: 
      - kong-net
    restart: on-failure

  kong: 
    image: kong:latest
    container_name: kong
    user: kong
    depends_on: 
      kong-database: 
        condition: service_healthy
    healthcheck: 
      test: "kong health"
      interval: 10s
      timeout: 5s
      retries: 5
    environment: 
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: '0.0.0.0:8001'
      KONG_ADMIN_LISTEN_SSL: '0.0.0.0:8444'
      KONG_PROXY_LISTEN: '0.0.0.0:8000'
      KONG_PROXY_LISTEN_SSL: '0.0.0.0:8443'
      KONG_CASSANDRA_CONTACT_POINTS: kong-database
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_DATABASE: kong
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kong
    networks: 
      - kong-net
    ports: 
      - 8000:8000
      - 8001:8001
      - 8443:8443
      - 8444:8444
    restart: on-failure
  
  konga: 
    image: pantsel/konga
    container_name: konga
    ports: 
      - 1337:1337
    networks: 
      - kong-net
    environment: 
      NODE_ENV: production
      TOKEN_SECRET: 123456