version: '3.7'

services: 
  apollo: 
    image: idoop/docker-apollo:latest
    container_name: apollo
    restart: always
    environment: 
      # 开启Portal,默认端口: 8070
      PORTAL_DB: jdbc:mysql://192.168.88.101:3306/ApolloPortalDB?characterEncoding=utf8
      PORTAL_DB_USER: root
      PORTAL_DB_PWD: whlx8888
      # 如果portal需要开启ldap或ad域验证,须设置该环境变量为TRUE
      #PORTAL_LDAP: "TRUE"
      
      # 开启dev环境, 默认端口: config 8080, admin 8090
      DEV_DB: jdbc:mysql://192.168.88.101:3306/ApolloConfigDB?characterEncoding=utf8
      DEV_DB_USER: root
      DEV_DB_PWD: whlx8888
    ports: 
      - 8070:8070
      - 9080:8080