version: '3.4'

services:
  #rabbitmq container
  rabbitmq:
    #use docker images
    image: rabbitmq:management-alpine
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER:admin
      - RABBITMQ_DEFAULT_PASS:admin
    networks:
      - rabbitmq
    #ports setting
    ports:
      - 15673:15672
      - 5673:5672
    restart: always
    #volumes setting
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq 
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
  
  redis:
    image: redis:alpine
    restart: on-failure
    ports:
      - 6379:6379  
    networks:
      - redis
  
  postgres:
    image: postgres
    container_name: db_postgres
    restart: on-failure
    environment:
      POSTGRES_DB: postgres_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postpwd
    ports:
      - 4352:5432
    networks:
      - postgres
    volumes:
      - postgresqldata:/var/lib/postgresql/data    

  # mysql:
    # image: mysql
    # container_name: local_mysql
    # entrypoint: ['/entrypoint.sh', '--default-authentication-plugin=mysql_native_password']
    # restart: always
    # volumes:
      # - mysqldata:/var/lib/mysql/
    # ports:
      # - 127.0.0.1:3306:3306
    # networks:
      # - mysql
    # environment:
      # - MYSQL_ROOT_PASSWORD=mysqlpwd

networks:
  rabbitmq:
    driver: bridge
  redis:
    driver: bridge
  postgres:
    driver: bridge
  # mysql:
    # driver: bridge
    
  
volumes:
  rabbitmqdata:
    driver: local
  postgresqldata:
    driver: local
  # mysqldata:
    # driver: local